services:
  - type: web
    name: voice-phishing-detection-backend
    env: python
    buildCommand: bash build.sh
    startCommand: uvicorn backend.app:app --host 0.0.0.0 --port 10000
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
